DSWeatherMoscow/Models/WeatherData.cs
namespace DSWeatherMoscow.Models;

public class WeatherData
{
    public int Id { get; set; }
    public DateTime Date { get; set; }
    public double? Temperature { get; set; }
    public double? AirHumidity { get; set; }
    public double? Td { get; set; }
    public double? AtmPressure { get; set; }
    public string? AirDirection { get; set; }
    public double? AirSpeed { get; set; }
    public double? Cloudiness { get; set; }
    public double? H { get; set; }
    public double? VV { get; set; }
    public string? WeatherEvents { get; set; }
}

DSWeatherMoscow/Controllers/HomeController.cs
namespace DSWeatherMoscow.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
}

DSWeatherMoscow/Controllers/WeatherController.cs
using DSWeatherMoscow.DbContexts;
using DSWeatherMoscow.Extensions;
using DSWeatherMoscow.Interfaces;
using DSWeatherMoscow.Models;

namespace DSWeatherMoscow.Controllers;

public class WeatherController : Controller
{
    private const string CacheKeyMin = "minYear";
    private const string CacheKeyMax = "maxYear";
    private readonly WeatherDbContext _context;
    private readonly IDBWrapper _idbWrapper;
    private readonly ILogger<WeatherController> _logger;
    private readonly IMemoryCache _memoryCache;


    public WeatherController(WeatherDbContext context, ILogger<WeatherController> logger, IMemoryCache memoryCache, IDBWrapper idbWrapper)
    {
        _context = context;
        _logger = logger;
        _memoryCache = memoryCache;
        _idbWrapper = idbWrapper;
    }

    public IActionResult ViewWeatherArchives(int? year, int? month, int page = 1, int pageSize = 50)
    {
        IQueryable<WeatherData> query = _context.WeatherData;
        if (year.HasValue)
        {
            query = query.Where(w => w.Date.Year == year);
        }

        if (month.HasValue)
        {
            query = query.Where(w => w.Date.Month == month);
        }


        // Try to get the value from the cache
        if (!_memoryCache.TryGetValue(CacheKeyMin, out int minYear))
        {
            if (_context.WeatherData.Any())
            {
                minYear = _context.WeatherData.Min(w => w.Date.Year);
                // Set cache options
                var cacheEntryOptions = new MemoryCacheEntryOptions().SetSlidingExpiration(TimeSpan.FromDays(1));
                // Set the value in cache
                _memoryCache.Set(CacheKeyMin, minYear, cacheEntryOptions);
            }
        }

        if (!_memoryCache.TryGetValue(CacheKeyMax, out int maxYear))
        {
            if (_context.WeatherData.Any())
            {
                maxYear = _context.WeatherData.Max(w => w.Date.Year);
                _memoryCache.Set(CacheKeyMax, maxYear, new MemoryCacheEntryOptions().SetSlidingExpiration(TimeSpan.FromDays(1)));
            }
        }

        ViewBag.MinYear = minYear;
        ViewBag.MaxYear = maxYear;
        ViewBag.Year = year;
        ViewBag.Month = month;

        var pagedWeatherArchives = query.OrderByDescending(w => w.Date).ToPagedList(page, pageSize);

        return View(pagedWeatherArchives);
    }


    public IActionResult UploadWeatherArchives()
    {
        return View();
    }

    [HttpPost]
    public IActionResult UploadWeatherArchives(List<IFormFile> files)
    {
        _idbWrapper.BeginTransaction();
        try
        {
            foreach (var file in files.Where(file => file.Length > 0))
            {
                using var stream = file.OpenReadStream();
                var workbook = new XSSFWorkbook(stream);
                foreach (var sheet in workbook)
                {
                    ProcessRow(sheet);
                }
            }
            _context.SaveChanges(); // Commit changes for all rows in the transaction
            _idbWrapper.Commit(); // Commit the transaction
            _memoryCache.Remove(CacheKeyMin);
            _memoryCache.Remove(CacheKeyMax);
        }
        catch (Exception e)
        {
            _idbWrapper.Rollback(); // Rollback the transaction in case of an error
            _logger.LogError(e, "Error with new file: {Ex}", e);
        }
        return RedirectToAction(nameof(ViewWeatherArchives));
    }

    private void ProcessRow(ISheet sheet)
    {
        for (var rowIdx = 5; rowIdx <= sheet.LastRowNum; rowIdx++)
        {
            var row = sheet.GetRow(rowIdx);
            if (row == null) continue;

            var weatherData = ParseRowToWeatherData(row);

            var existingRecord = _context.WeatherData?.FirstOrDefault(w => w.Date == weatherData.Date);

            if (existingRecord != null)
            {
                UpdateExistingRecord(existingRecord, weatherData);
                _context.WeatherData?.Update(existingRecord);
            }
            else
            {
                _context.WeatherData?.Add(weatherData);
            }
        }
    }

    private static WeatherData ParseRowToWeatherData(IRow row)
    {
        var date = Convert.ToDateTime(row.GetCell(0, MissingCellPolicy.RETURN_NULL_AND_BLANK).ParseCellAsString());
        var time = Convert.ToDateTime(row.GetCell(1, MissingCellPolicy.RETURN_NULL_AND_BLANK).ParseCellAsString());
        var weatherData = new WeatherData {
            Date = DateTime.SpecifyKind(
                new DateTime(date.Year, date.Month, date.Day, time.Hour, time.Minute, time.Second),
                DateTimeKind.Utc),
            Temperature = row.GetCell(2, MissingCellPolicy.RETURN_NULL_AND_BLANK).ParseCellAsDouble(),
            AirHumidity = row.GetCell(3, MissingCellPolicy.RETURN_NULL_AND_BLANK).ParseCellAsDouble(),
            Td = row.GetCell(4, MissingCellPolicy.RETURN_NULL_AND_BLANK).ParseCellAsDouble(),
            AtmPressure = row.GetCell(5, MissingCellPolicy.RETURN_NULL_AND_BLANK).ParseCellAsDouble(),
            AirDirection = row.GetCell(6, MissingCellPolicy.RETURN_NULL_AND_BLANK).ParseCellAsString(),
            AirSpeed = row.GetCell(7, MissingCellPolicy.RETURN_NULL_AND_BLANK).ParseCellAsDouble(),
            Cloudiness = row.GetCell(8, MissingCellPolicy.RETURN_NULL_AND_BLANK).ParseCellAsDouble(),
            H = row.GetCell(9, MissingCellPolicy.RETURN_NULL_AND_BLANK).ParseCellAsDouble(),
            VV = row.GetCell(10, MissingCellPolicy.RETURN_NULL_AND_BLANK).ParseCellAsDouble(),
            WeatherEvents = row.GetCell(11, MissingCellPolicy.RETURN_NULL_AND_BLANK).ParseCellAsString()
        };
        return weatherData;
    }

    private static void UpdateExistingRecord(WeatherData existingRecord, WeatherData newData)
    {
        var properties = typeof(WeatherData).GetProperties()
            .Where(p => p is {CanRead: true, CanWrite: true} && p.Name != nameof(WeatherData.Id));

        foreach (var property in properties)
        {
            var newValue = property.GetValue(newData);
            property.SetValue(existingRecord, newValue);
        }
    }
}

DSWeatherMoscow/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <form asp-controller="Weather" asp-action="ViewWeatherArchives" method="post">
        <button type="submit" class="btn btn-primary">Display Weather Data page</button>
    </form>
    <form asp-controller="Weather" asp-action="UploadWeatherArchives" method="get">
        <button type="submit" class="btn btn-primary">Upload page</button>
    </form>
</div>

DSWeatherMoscow/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - DSWeatherMoscow</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/DSWeatherMoscow.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DSWeatherMoscow</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">

</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>

DSWeatherMoscow/Views/Weather/UploadWeatherArchives.cshtml
<h2>Upload Weather Archives</h2>

<form method="post" asp-controller="Weather" asp-action="UploadWeatherArchives" enctype="multipart/form-data">
    <div class="form-group">
        <label for="files">Select Excel Files:</label>
        <input type="file" name="files" id="files" multiple required/>
    </div>
    <button type="submit" class="btn btn-primary" id="uploadButton">Upload</button>
</form>

DSWeatherMoscow/Views/Weather/ViewWeatherArchives.cshtml
@using X.PagedList.Mvc.Core
@model IPagedList<WeatherData>

<h2>Weather Archives</h2>
<form method="get" asp-controller="Weather" asp-action="ViewWeatherArchives">
    <label for="year">Select Year:</label>
    <select id="year" name="year">
        <option value="">All Years</option>
        @{for (var i = ViewBag.MaxYear; i >= ViewBag.MinYear; i--)
          {
              <option value="@i" selected="@(ViewBag.Year != null && i == ViewBag.Year)">@i</option>
          }
        }
    </select>
    <label for="month">Select Month:</label>
    <select id="month" name="month">
        <option value="">All Months</option>
        @{for (var i = 1; i <= 12; i++)
          {
              <option value="@i" selected="@(ViewBag.Month != null && i == ViewBag.Month)">@DateTimeFormatInfo.CurrentInfo.GetMonthName(i)</option>
          }
        }
    </select>
    <button type="submit">Filter</button>
</form>

<table class="table">
    <thead>
    <tr>
        <th>Date</th>
        <th>Temperature</th>
        <th>Air Humidity</th>
        <th>Td</th>
        <th>Atmospheric Pressure</th>
        <th>AirDirection</th>
        <th>AirSpeed</th>
        <th>Cloudiness</th>
        <th>H</th>
        <th>VV</th>
        <th>WeatherEvents</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var data in Model)
    {
        <tr>
            <td>@data.Date</td>
            <td>@data.Temperature</td>
            <td>@data.AirHumidity</td>
            <td>@data.Td</td>
            <td>@data.AtmPressure</td>
            <td>@data.AirDirection</td>
            <td>@data.AirSpeed</td>
            <td>@data.Cloudiness</td>
            <td>@data.H</td>
            <td>@data.VV</td>
            <td>@data.WeatherEvents</td>
        </tr>
    }
    </tbody>
</table>


<div class="text-center">
    @Html.PagedListPager(Model, page => Url.Action("ViewWeatherArchives", new {
        page,
        year = ViewBag.Year,
        month = ViewBag.Month
    }))
</div>